/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 11
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/llamacpp-embedding/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
*   - @qvac/sdk/bci-whispercpp-transcription/plugin
*   - @qvac/sdk/parakeet-transcription/plugin
*   - @qvac/sdk/nmtcpp-translation/plugin
*   - @qvac/sdk/tts-ggml/plugin
*   - @qvac/sdk/ggml-ocr/plugin
*   - @qvac/sdk/sdcpp-generation/plugin
*   - @qvac/sdk/ggml-vla/plugin
*   - @qvac/sdk/ggml-classification/plugin
 */

import { initializeWorkerCore, ensureRPCSetup } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/worker-core.js";
import { registerPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/plugins/index.js";
import { getServerLogger } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/logging/index.js";

import { llmPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/llamacpp-completion/plugin.js";
import { embeddingsPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/llamacpp-embedding/plugin.js";
import { whisperPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/whispercpp-transcription/plugin.js";
import { bciPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/bci-whispercpp-transcription/plugin.js";
import { parakeetPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/parakeet-transcription/plugin.js";
import { nmtPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/nmtcpp-translation/plugin.js";
import { ttsPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/tts-ggml/plugin.js";
import { ocrPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/ggml-ocr/plugin.js";
import { diffusionPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/sdcpp-generation/plugin.js";
import { vlaPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/ggml-vla/plugin.js";
import { classificationPlugin } from "file:///workspaces/bolt/node_modules/@qvac/sdk/dist/server/bare/plugins/ggml-classification/plugin.js";

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 11");

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);
registerPlugin(whisperPlugin);
registerPlugin(bciPlugin);
registerPlugin(parakeetPlugin);
registerPlugin(nmtPlugin);
registerPlugin(ttsPlugin);
registerPlugin(ocrPlugin);
registerPlugin(diffusionPlugin);
registerPlugin(vlaPlugin);
registerPlugin(classificationPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
