// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@bolt/joinChannel', 0],
  [0, '@bolt/joinChannel'],
  ['@bolt/leaveChannel', 1],
  [1, '@bolt/leaveChannel'],
  ['@bolt/getFeed', 2],
  [2, '@bolt/getFeed'],
  ['@bolt/initChannel', 3],
  [3, '@bolt/initChannel'],
  ['@bolt/uploadVideo', 4],
  [4, '@bolt/uploadVideo'],
  ['@bolt/getUploads', 5],
  [5, '@bolt/getUploads'],
  ['@bolt/startStream', 6],
  [6, '@bolt/startStream'],
  ['@bolt/injectEvent', 7],
  [7, '@bolt/injectEvent'],
  ['@bolt/downloadVideo', 8],
  [8, '@bolt/downloadVideo'],
  ['@bolt/workerReady', 9],
  [9, '@bolt/workerReady'],
  ['@bolt/channelEvent', 10],
  [10, '@bolt/channelEvent'],
  ['@bolt/uploadProgress', 11],
  [11, '@bolt/uploadProgress'],
  ['@bolt/downloadProgress', 12],
  [12, '@bolt/downloadProgress'],
  ['@bolt/errorEvent', 13],
  [13, '@bolt/errorEvent'],
  ['@bolt/initWorker', 14],
  [14, '@bolt/initWorker']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@bolt/joinChannel', getEncoding('@bolt/join-channel-request')],
      ['@bolt/leaveChannel', getEncoding('@bolt/join-channel-request')],
      ['@bolt/getFeed', getEncoding('@bolt/empty-request')],
      ['@bolt/initChannel', getEncoding('@bolt/init-channel-request')],
      ['@bolt/uploadVideo', getEncoding('@bolt/upload-video-request')],
      ['@bolt/getUploads', getEncoding('@bolt/empty-request')],
      ['@bolt/startStream', getEncoding('@bolt/start-stream-request')],
      ['@bolt/injectEvent', getEncoding('@bolt/inject-event-request')],
      ['@bolt/downloadVideo', getEncoding('@bolt/download-video-request')],
      ['@bolt/workerReady', getEncoding('@bolt/empty-request')],
      ['@bolt/channelEvent', getEncoding('@bolt/channel-event')],
      ['@bolt/uploadProgress', getEncoding('@bolt/upload-progress')],
      ['@bolt/downloadProgress', getEncoding('@bolt/download-progress')],
      ['@bolt/errorEvent', getEncoding('@bolt/error-event')],
      ['@bolt/initWorker', getEncoding('@bolt/init-worker-request')]
    ])
    this._responseEncodings = new Map([
      ['@bolt/joinChannel', getEncoding('@bolt/channel-response')],
      ['@bolt/leaveChannel', getEncoding('@bolt/channel-response')],
      ['@bolt/getFeed', getEncoding('@bolt/get-feed-response')],
      ['@bolt/initChannel', getEncoding('@bolt/init-channel-response')],
      ['@bolt/uploadVideo', getEncoding('@bolt/upload-video-response')],
      ['@bolt/getUploads', getEncoding('@bolt/get-uploads-response')],
      ['@bolt/startStream', getEncoding('@bolt/start-stream-response')],
      ['@bolt/injectEvent', getEncoding('@bolt/success-response')],
      ['@bolt/downloadVideo', getEncoding('@bolt/download-video-response')],
      ['@bolt/initWorker', getEncoding('@bolt/init-worker-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async joinChannel(args) {
    return this._call('@bolt/joinChannel', args)
  }

  async leaveChannel(args) {
    return this._call('@bolt/leaveChannel', args)
  }

  async getFeed(args) {
    return this._call('@bolt/getFeed', args)
  }

  async initChannel(args) {
    return this._call('@bolt/initChannel', args)
  }

  async uploadVideo(args) {
    return this._call('@bolt/uploadVideo', args)
  }

  async getUploads(args) {
    return this._call('@bolt/getUploads', args)
  }

  async startStream(args) {
    return this._call('@bolt/startStream', args)
  }

  async injectEvent(args) {
    return this._call('@bolt/injectEvent', args)
  }

  async downloadVideo(args) {
    return this._call('@bolt/downloadVideo', args)
  }

  workerReady(args) {
    return this._callSync('@bolt/workerReady', args)
  }

  channelEvent(args) {
    return this._callSync('@bolt/channelEvent', args)
  }

  uploadProgress(args) {
    return this._callSync('@bolt/uploadProgress', args)
  }

  downloadProgress(args) {
    return this._callSync('@bolt/downloadProgress', args)
  }

  errorEvent(args) {
    return this._callSync('@bolt/errorEvent', args)
  }

  async initWorker(args) {
    return this._call('@bolt/initWorker', args)
  }

  onJoinChannel(responseFn) {
    this._handlers['@bolt/joinChannel'] = responseFn
  }

  onLeaveChannel(responseFn) {
    this._handlers['@bolt/leaveChannel'] = responseFn
  }

  onGetFeed(responseFn) {
    this._handlers['@bolt/getFeed'] = responseFn
  }

  onInitChannel(responseFn) {
    this._handlers['@bolt/initChannel'] = responseFn
  }

  onUploadVideo(responseFn) {
    this._handlers['@bolt/uploadVideo'] = responseFn
  }

  onGetUploads(responseFn) {
    this._handlers['@bolt/getUploads'] = responseFn
  }

  onStartStream(responseFn) {
    this._handlers['@bolt/startStream'] = responseFn
  }

  onInjectEvent(responseFn) {
    this._handlers['@bolt/injectEvent'] = responseFn
  }

  onDownloadVideo(responseFn) {
    this._handlers['@bolt/downloadVideo'] = responseFn
  }

  onWorkerReady(responseFn) {
    this._handlers['@bolt/workerReady'] = responseFn
  }

  onChannelEvent(responseFn) {
    this._handlers['@bolt/channelEvent'] = responseFn
  }

  onUploadProgress(responseFn) {
    this._handlers['@bolt/uploadProgress'] = responseFn
  }

  onDownloadProgress(responseFn) {
    this._handlers['@bolt/downloadProgress'] = responseFn
  }

  onErrorEvent(responseFn) {
    this._handlers['@bolt/errorEvent'] = responseFn
  }

  onInitWorker(responseFn) {
    this._handlers['@bolt/initWorker'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@bolt/workerReady',
      '@bolt/channelEvent',
      '@bolt/uploadProgress',
      '@bolt/downloadProgress',
      '@bolt/errorEvent'
    ].includes(command)
  }
}

module.exports = HRPC
