// This file is autogenerated by the hyperschema compiler
// Schema Version: 5
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 5

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bolt/join-channel-request
const encoding0 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
  },
  encode(state, m) {
    const flags = m.channelKey ? 1 : 0

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/channel-response
const encoding1 = encoding0

// @bolt/empty-request
const encoding2 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @bolt/init-worker-request.ownedChannels
const encoding3_0 = c.array(c.string)

// @bolt/init-worker-request
const encoding3 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.ownedChannels) encoding3_0.preencode(state, m.ownedChannels)
  },
  encode(state, m) {
    const flags = m.ownedChannels ? 1 : 0

    c.uint.encode(state, flags)

    if (m.ownedChannels) encoding3_0.encode(state, m.ownedChannels)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      ownedChannels: (flags & 1) !== 0 ? encoding3_0.decode(state) : null
    }
  }
}

// @bolt/init-worker-response
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.success ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      success: (flags & 1) !== 0
    }
  }
}

// @bolt/get-feed-response
const encoding5 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.itemsJson) c.string.preencode(state, m.itemsJson)
  },
  encode(state, m) {
    const flags = m.itemsJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.itemsJson) c.string.encode(state, m.itemsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      itemsJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/init-channel-request
const encoding6 = {
  preencode(state, m) {
    state.end++ // max flag is 16 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatarPath) c.string.preencode(state, m.avatarPath)
    if (version >= 3 && m.delegateDescription) c.string.preencode(state, m.delegateDescription)
  },
  encode(state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.description ? 2 : 0) |
      (m.avatarPath ? 4 : 0) |
      ((version >= 3 && m.isDelegate) ? 8 : 0) |
      ((version >= 3 && m.delegateDescription) ? 16 : 0)

    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatarPath) c.string.encode(state, m.avatarPath)
    if (version >= 3 && m.delegateDescription) c.string.encode(state, m.delegateDescription)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatarPath: (flags & 4) !== 0 ? c.string.decode(state) : null,
      isDelegate: (version >= 3 && (flags & 8) !== 0),
      delegateDescription: (version >= 3 && (flags & 16) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/init-channel-response
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.publicKey) c.string.preencode(state, m.publicKey)
    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = (m.publicKey ? 1 : 0) | (m.name ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.publicKey) c.string.encode(state, m.publicKey)
    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      publicKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      name: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/upload-video-request
const encoding8 = {
  preencode(state, m) {
    const flags =
      (m.filePath ? 1 : 0) |
      (m.title ? 2 : 0) |
      (m.duration ? 4 : 0) |
      (m.thumbnailPath ? 8 : 0) |
      (m.channelKey ? 16 : 0) |
      ((version >= 3 && m.videoType) ? 32 : 0) |
      ((version >= 3 && m.homeTeam) ? 64 : 0) |
      ((version >= 3 && m.awayTeam) ? 128 : 0) |
      ((version >= 3 && m.homeScore) ? 256 : 0) |
      ((version >= 3 && m.awayScore) ? 512 : 0) |
      ((version >= 5 && m.tournamentName) ? 1024 : 0) |
      ((version >= 5 && m.matchDate) ? 2048 : 0) |
      ((version >= 5 && m.transcriptPath) ? 4096 : 0) |
      ((version >= 5 && m.eventsJson) ? 8192 : 0)

    c.uint.preencode(state, flags)

    if (m.filePath) c.string.preencode(state, m.filePath)
    if (m.title) c.string.preencode(state, m.title)
    if (m.duration) c.string.preencode(state, m.duration)
    if (m.thumbnailPath) c.string.preencode(state, m.thumbnailPath)
    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (version >= 3 && m.videoType) c.string.preencode(state, m.videoType)
    if (version >= 3 && m.homeTeam) c.string.preencode(state, m.homeTeam)
    if (version >= 3 && m.awayTeam) c.string.preencode(state, m.awayTeam)
    if (version >= 3 && m.homeScore) c.string.preencode(state, m.homeScore)
    if (version >= 3 && m.awayScore) c.string.preencode(state, m.awayScore)
    if (version >= 5 && m.tournamentName) c.string.preencode(state, m.tournamentName)
    if (version >= 5 && m.matchDate) c.string.preencode(state, m.matchDate)
    if (version >= 5 && m.transcriptPath) c.string.preencode(state, m.transcriptPath)
    if (version >= 5 && m.eventsJson) c.string.preencode(state, m.eventsJson)
  },
  encode(state, m) {
    const flags =
      (m.filePath ? 1 : 0) |
      (m.title ? 2 : 0) |
      (m.duration ? 4 : 0) |
      (m.thumbnailPath ? 8 : 0) |
      (m.channelKey ? 16 : 0) |
      ((version >= 3 && m.videoType) ? 32 : 0) |
      ((version >= 3 && m.homeTeam) ? 64 : 0) |
      ((version >= 3 && m.awayTeam) ? 128 : 0) |
      ((version >= 3 && m.homeScore) ? 256 : 0) |
      ((version >= 3 && m.awayScore) ? 512 : 0) |
      ((version >= 5 && m.tournamentName) ? 1024 : 0) |
      ((version >= 5 && m.matchDate) ? 2048 : 0) |
      ((version >= 5 && m.transcriptPath) ? 4096 : 0) |
      ((version >= 5 && m.eventsJson) ? 8192 : 0)

    c.uint.encode(state, flags)

    if (m.filePath) c.string.encode(state, m.filePath)
    if (m.title) c.string.encode(state, m.title)
    if (m.duration) c.string.encode(state, m.duration)
    if (m.thumbnailPath) c.string.encode(state, m.thumbnailPath)
    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (version >= 3 && m.videoType) c.string.encode(state, m.videoType)
    if (version >= 3 && m.homeTeam) c.string.encode(state, m.homeTeam)
    if (version >= 3 && m.awayTeam) c.string.encode(state, m.awayTeam)
    if (version >= 3 && m.homeScore) c.string.encode(state, m.homeScore)
    if (version >= 3 && m.awayScore) c.string.encode(state, m.awayScore)
    if (version >= 5 && m.tournamentName) c.string.encode(state, m.tournamentName)
    if (version >= 5 && m.matchDate) c.string.encode(state, m.matchDate)
    if (version >= 5 && m.transcriptPath) c.string.encode(state, m.transcriptPath)
    if (version >= 5 && m.eventsJson) c.string.encode(state, m.eventsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      filePath: (flags & 1) !== 0 ? c.string.decode(state) : null,
      title: (flags & 2) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 4) !== 0 ? c.string.decode(state) : null,
      thumbnailPath: (flags & 8) !== 0 ? c.string.decode(state) : null,
      channelKey: (flags & 16) !== 0 ? c.string.decode(state) : null,
      videoType: (version >= 3 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      homeTeam: (version >= 3 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      awayTeam: (version >= 3 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      homeScore: (version >= 3 && (flags & 256) !== 0) ? c.string.decode(state) : null,
      awayScore: (version >= 3 && (flags & 512) !== 0) ? c.string.decode(state) : null,
      tournamentName: (version >= 5 && (flags & 1024) !== 0) ? c.string.decode(state) : null,
      matchDate: (version >= 5 && (flags & 2048) !== 0) ? c.string.decode(state) : null,
      transcriptPath: (version >= 5 && (flags & 4096) !== 0) ? c.string.decode(state) : null,
      eventsJson: (version >= 5 && (flags & 8192) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/upload-video-response
const encoding9 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.videoJson) c.string.preencode(state, m.videoJson)
  },
  encode(state, m) {
    const flags = m.videoJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.videoJson) c.string.encode(state, m.videoJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/get-uploads-request
const encoding10 = encoding0

// @bolt/get-uploads-response
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.channelJson) c.string.preencode(state, m.channelJson)
  },
  encode(state, m) {
    const flags = m.channelJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.channelJson) c.string.encode(state, m.channelJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/get-channels-request
const encoding12 = encoding2

// @bolt/get-channels-response
const encoding13 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.channelsJson) c.string.preencode(state, m.channelsJson)
  },
  encode(state, m) {
    const flags = m.channelsJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.channelsJson) c.string.encode(state, m.channelsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelsJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/start-stream-request
const encoding14 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
  },
  encode(state, m) {
    const flags = (m.channelKey ? 1 : 0) | (m.videoId ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/start-stream-response
const encoding15 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.url) c.string.preencode(state, m.url)
    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
  },
  encode(state, m) {
    const flags = (m.url ? 1 : 0) | (m.channelKey ? 2 : 0) | (m.videoId ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.url) c.string.encode(state, m.url)
    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      url: (flags & 1) !== 0 ? c.string.decode(state) : null,
      channelKey: (flags & 2) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/inject-event-request
const encoding16 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.eventJson) c.string.preencode(state, m.eventJson)
  },
  encode(state, m) {
    const flags = m.eventJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.eventJson) c.string.encode(state, m.eventJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      eventJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/success-response
const encoding17 = encoding4

// @bolt/download-video-request
const encoding18 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.destinationPath) c.string.preencode(state, m.destinationPath)
  },
  encode(state, m) {
    const flags = (m.channelKey ? 1 : 0) | (m.videoId ? 2 : 0) | (m.destinationPath ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.destinationPath) c.string.encode(state, m.destinationPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 2) !== 0 ? c.string.decode(state) : null,
      destinationPath: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/download-video-response
const encoding19 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.destinationPath) c.string.preencode(state, m.destinationPath)
  },
  encode(state, m) {
    const flags = m.destinationPath ? 1 : 0

    c.uint.encode(state, flags)

    if (m.destinationPath) c.string.encode(state, m.destinationPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      destinationPath: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/channel-event
const encoding20 = encoding16

// @bolt/upload-progress
const encoding21 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.percent) c.uint.preencode(state, m.percent)
  },
  encode(state, m) {
    const flags = (m.videoId ? 1 : 0) | (m.percent ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.percent) c.uint.encode(state, m.percent)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      percent: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bolt/download-progress
const encoding22 = {
  preencode(state, m) {
    state.end++ // max flag is 16 so always one byte

    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.percent) c.uint.preencode(state, m.percent)
    if (m.bytesReceived) c.uint.preencode(state, m.bytesReceived)
    if (m.totalBytes) c.uint.preencode(state, m.totalBytes)
  },
  encode(state, m) {
    const flags =
      (m.videoId ? 1 : 0) |
      (m.channelKey ? 2 : 0) |
      (m.percent ? 4 : 0) |
      (m.bytesReceived ? 8 : 0) |
      (m.totalBytes ? 16 : 0)

    c.uint.encode(state, flags)

    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.percent) c.uint.encode(state, m.percent)
    if (m.bytesReceived) c.uint.encode(state, m.bytesReceived)
    if (m.totalBytes) c.uint.encode(state, m.totalBytes)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      channelKey: (flags & 2) !== 0 ? c.string.decode(state) : null,
      percent: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      bytesReceived: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      totalBytes: (flags & 16) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bolt/error-event
const encoding23 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.message) c.string.preencode(state, m.message)
    if (m.command) c.string.preencode(state, m.command)
  },
  encode(state, m) {
    const flags = (m.message ? 1 : 0) | (m.command ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
    if (m.command) c.string.encode(state, m.command)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      message: (flags & 1) !== 0 ? c.string.decode(state) : null,
      command: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/rag-query-request
const encoding24 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.workspaceId) c.string.preencode(state, m.workspaceId)
    if (version >= 2 && m.query) c.string.preencode(state, m.query)
  },
  encode(state, m) {
    const flags = ((version >= 2 && m.workspaceId) ? 1 : 0) | ((version >= 2 && m.query) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.workspaceId) c.string.encode(state, m.workspaceId)
    if (version >= 2 && m.query) c.string.encode(state, m.query)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      workspaceId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      query: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/rag-query-response
const encoding25 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.resultsJson) c.string.preencode(state, m.resultsJson)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.resultsJson) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 2 && m.resultsJson) c.string.encode(state, m.resultsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      resultsJson: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/load-model-request
const encoding26 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 4 && m.modelSrc) c.string.preencode(state, m.modelSrc)
    if (version >= 4 && m.modelType) c.string.preencode(state, m.modelType)
  },
  encode(state, m) {
    const flags = ((version >= 4 && m.modelSrc) ? 1 : 0) | ((version >= 4 && m.modelType) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 4 && m.modelSrc) c.string.encode(state, m.modelSrc)
    if (version >= 4 && m.modelType) c.string.encode(state, m.modelType)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      modelSrc: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      modelType: (version >= 4 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/load-model-response
const encoding27 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.modelId) c.string.preencode(state, m.modelId)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.modelId) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 4 && m.modelId) c.string.encode(state, m.modelId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      modelId: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/unload-model-request
const encoding28 = encoding27

// @bolt/unload-model-response
const encoding29 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 4 && m.success) ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      success: (version >= 4 && (flags & 1) !== 0)
    }
  }
}

// @bolt/infer-request
const encoding30 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 4 && m.modelId) c.string.preencode(state, m.modelId)
    if (version >= 4 && m.optionsJson) c.string.preencode(state, m.optionsJson)
  },
  encode(state, m) {
    const flags = ((version >= 4 && m.modelId) ? 1 : 0) | ((version >= 4 && m.optionsJson) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 4 && m.modelId) c.string.encode(state, m.modelId)
    if (version >= 4 && m.optionsJson) c.string.encode(state, m.optionsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      modelId: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      optionsJson: (version >= 4 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/infer-response
const encoding31 = encoding29

// @bolt/completion-stream
const encoding32 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.token) c.string.preencode(state, m.token)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.token) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 4 && m.token) c.string.encode(state, m.token)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      token: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/completion-tool-call
const encoding33 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.call) c.string.preencode(state, m.call)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.call) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 4 && m.call) c.string.encode(state, m.call)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      call: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @bolt/model-progress
const encoding34 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 4 && m.progressJson) c.string.preencode(state, m.progressJson)
  },
  encode(state, m) {
    const flags = (version >= 4 && m.progressJson) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 4 && m.progressJson) c.string.encode(state, m.progressJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      progressJson: (version >= 4 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bolt/join-channel-request':
      return encoding0
    case '@bolt/channel-response':
      return encoding1
    case '@bolt/empty-request':
      return encoding2
    case '@bolt/init-worker-request':
      return encoding3
    case '@bolt/init-worker-response':
      return encoding4
    case '@bolt/get-feed-response':
      return encoding5
    case '@bolt/init-channel-request':
      return encoding6
    case '@bolt/init-channel-response':
      return encoding7
    case '@bolt/upload-video-request':
      return encoding8
    case '@bolt/upload-video-response':
      return encoding9
    case '@bolt/get-uploads-request':
      return encoding10
    case '@bolt/get-uploads-response':
      return encoding11
    case '@bolt/get-channels-request':
      return encoding12
    case '@bolt/get-channels-response':
      return encoding13
    case '@bolt/start-stream-request':
      return encoding14
    case '@bolt/start-stream-response':
      return encoding15
    case '@bolt/inject-event-request':
      return encoding16
    case '@bolt/success-response':
      return encoding17
    case '@bolt/download-video-request':
      return encoding18
    case '@bolt/download-video-response':
      return encoding19
    case '@bolt/channel-event':
      return encoding20
    case '@bolt/upload-progress':
      return encoding21
    case '@bolt/download-progress':
      return encoding22
    case '@bolt/error-event':
      return encoding23
    case '@bolt/rag-query-request':
      return encoding24
    case '@bolt/rag-query-response':
      return encoding25
    case '@bolt/load-model-request':
      return encoding26
    case '@bolt/load-model-response':
      return encoding27
    case '@bolt/unload-model-request':
      return encoding28
    case '@bolt/unload-model-response':
      return encoding29
    case '@bolt/infer-request':
      return encoding30
    case '@bolt/infer-response':
      return encoding31
    case '@bolt/completion-stream':
      return encoding32
    case '@bolt/completion-tool-call':
      return encoding33
    case '@bolt/model-progress':
      return encoding34
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
