// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bolt/join-channel-request
const encoding0 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
  },
  encode(state, m) {
    const flags = m.channelKey ? 1 : 0

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/channel-response
const encoding1 = encoding0

// @bolt/empty-request
const encoding2 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @bolt/get-feed-response
const encoding3 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.itemsJson) c.string.preencode(state, m.itemsJson)
  },
  encode(state, m) {
    const flags = m.itemsJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.itemsJson) c.string.encode(state, m.itemsJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      itemsJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/init-channel-request
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    if (m.description) c.string.preencode(state, m.description)
    if (m.avatarPath) c.string.preencode(state, m.avatarPath)
  },
  encode(state, m) {
    const flags = (m.name ? 1 : 0) | (m.description ? 2 : 0) | (m.avatarPath ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.description) c.string.encode(state, m.description)
    if (m.avatarPath) c.string.encode(state, m.avatarPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      description: (flags & 2) !== 0 ? c.string.decode(state) : null,
      avatarPath: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/init-channel-response
const encoding5 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.publicKey) c.string.preencode(state, m.publicKey)
    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = (m.publicKey ? 1 : 0) | (m.name ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.publicKey) c.string.encode(state, m.publicKey)
    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      publicKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      name: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/upload-video-request
const encoding6 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.filePath) c.string.preencode(state, m.filePath)
    if (m.title) c.string.preencode(state, m.title)
    if (m.duration) c.string.preencode(state, m.duration)
    if (m.thumbnailPath) c.string.preencode(state, m.thumbnailPath)
  },
  encode(state, m) {
    const flags =
      (m.filePath ? 1 : 0) | (m.title ? 2 : 0) | (m.duration ? 4 : 0) | (m.thumbnailPath ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.filePath) c.string.encode(state, m.filePath)
    if (m.title) c.string.encode(state, m.title)
    if (m.duration) c.string.encode(state, m.duration)
    if (m.thumbnailPath) c.string.encode(state, m.thumbnailPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      filePath: (flags & 1) !== 0 ? c.string.decode(state) : null,
      title: (flags & 2) !== 0 ? c.string.decode(state) : null,
      duration: (flags & 4) !== 0 ? c.string.decode(state) : null,
      thumbnailPath: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/upload-video-response
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.videoJson) c.string.preencode(state, m.videoJson)
  },
  encode(state, m) {
    const flags = m.videoJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.videoJson) c.string.encode(state, m.videoJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/get-uploads-response
const encoding8 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.channelJson) c.string.preencode(state, m.channelJson)
  },
  encode(state, m) {
    const flags = m.channelJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.channelJson) c.string.encode(state, m.channelJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/start-stream-request
const encoding9 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
  },
  encode(state, m) {
    const flags = (m.channelKey ? 1 : 0) | (m.videoId ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/start-stream-response
const encoding10 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.url) c.string.preencode(state, m.url)
    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
  },
  encode(state, m) {
    const flags = (m.url ? 1 : 0) | (m.channelKey ? 2 : 0) | (m.videoId ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.url) c.string.encode(state, m.url)
    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      url: (flags & 1) !== 0 ? c.string.decode(state) : null,
      channelKey: (flags & 2) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/inject-event-request
const encoding11 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.eventJson) c.string.preencode(state, m.eventJson)
  },
  encode(state, m) {
    const flags = m.eventJson ? 1 : 0

    c.uint.encode(state, flags)

    if (m.eventJson) c.string.encode(state, m.eventJson)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      eventJson: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/success-response
const encoding12 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.success ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      success: (flags & 1) !== 0
    }
  }
}

// @bolt/download-video-request
const encoding13 = {
  preencode(state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.destinationPath) c.string.preencode(state, m.destinationPath)
  },
  encode(state, m) {
    const flags = (m.channelKey ? 1 : 0) | (m.videoId ? 2 : 0) | (m.destinationPath ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.destinationPath) c.string.encode(state, m.destinationPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      channelKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      videoId: (flags & 2) !== 0 ? c.string.decode(state) : null,
      destinationPath: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/download-video-response
const encoding14 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.destinationPath) c.string.preencode(state, m.destinationPath)
  },
  encode(state, m) {
    const flags = m.destinationPath ? 1 : 0

    c.uint.encode(state, flags)

    if (m.destinationPath) c.string.encode(state, m.destinationPath)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      destinationPath: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bolt/channel-event
const encoding15 = encoding11

// @bolt/upload-progress
const encoding16 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.percent) c.uint.preencode(state, m.percent)
  },
  encode(state, m) {
    const flags = (m.videoId ? 1 : 0) | (m.percent ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.percent) c.uint.encode(state, m.percent)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      percent: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bolt/download-progress
const encoding17 = {
  preencode(state, m) {
    state.end++ // max flag is 16 so always one byte

    if (m.videoId) c.string.preencode(state, m.videoId)
    if (m.channelKey) c.string.preencode(state, m.channelKey)
    if (m.percent) c.uint.preencode(state, m.percent)
    if (m.bytesReceived) c.uint.preencode(state, m.bytesReceived)
    if (m.totalBytes) c.uint.preencode(state, m.totalBytes)
  },
  encode(state, m) {
    const flags =
      (m.videoId ? 1 : 0) |
      (m.channelKey ? 2 : 0) |
      (m.percent ? 4 : 0) |
      (m.bytesReceived ? 8 : 0) |
      (m.totalBytes ? 16 : 0)

    c.uint.encode(state, flags)

    if (m.videoId) c.string.encode(state, m.videoId)
    if (m.channelKey) c.string.encode(state, m.channelKey)
    if (m.percent) c.uint.encode(state, m.percent)
    if (m.bytesReceived) c.uint.encode(state, m.bytesReceived)
    if (m.totalBytes) c.uint.encode(state, m.totalBytes)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      videoId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      channelKey: (flags & 2) !== 0 ? c.string.decode(state) : null,
      percent: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      bytesReceived: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      totalBytes: (flags & 16) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @bolt/error-event
const encoding18 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.message) c.string.preencode(state, m.message)
    if (m.command) c.string.preencode(state, m.command)
  },
  encode(state, m) {
    const flags = (m.message ? 1 : 0) | (m.command ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
    if (m.command) c.string.encode(state, m.command)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      message: (flags & 1) !== 0 ? c.string.decode(state) : null,
      command: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bolt/join-channel-request':
      return encoding0
    case '@bolt/channel-response':
      return encoding1
    case '@bolt/empty-request':
      return encoding2
    case '@bolt/get-feed-response':
      return encoding3
    case '@bolt/init-channel-request':
      return encoding4
    case '@bolt/init-channel-response':
      return encoding5
    case '@bolt/upload-video-request':
      return encoding6
    case '@bolt/upload-video-response':
      return encoding7
    case '@bolt/get-uploads-response':
      return encoding8
    case '@bolt/start-stream-request':
      return encoding9
    case '@bolt/start-stream-response':
      return encoding10
    case '@bolt/inject-event-request':
      return encoding11
    case '@bolt/success-response':
      return encoding12
    case '@bolt/download-video-request':
      return encoding13
    case '@bolt/download-video-response':
      return encoding14
    case '@bolt/channel-event':
      return encoding15
    case '@bolt/upload-progress':
      return encoding16
    case '@bolt/download-progress':
      return encoding17
    case '@bolt/error-event':
      return encoding18
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
