import React, { useEffect, useRef } from 'react'
import { AssistantRuntimeProvider, useLocalRuntime } from '@assistant-ui/react'
import { Thread } from './assistant-ui/thread' // Scaffolding generated by 'npx assistant-ui init'
import { createQvacModelAdapter } from '../lib/qvac-adapter'
import type { ChannelEvent } from '../../../shared/types'

interface ChatInterfaceProps {
    modelStatus: string
    modelProgress: number
    loadModel: () => void
    channelKey?: string | null
}

export function ChatInterface({ modelStatus, modelProgress, loadModel, channelKey }: ChatInterfaceProps): React.JSX.Element {
    // Accumulate channel events for AI context injection
    const channelEventsRef = useRef<ChannelEvent[]>([])

    // Create the adapter with a ref to the events buffer
    const adapter = React.useMemo(
        () => createQvacModelAdapter(channelEventsRef),
        []
    )

    const runtime = useLocalRuntime(adapter)

    // Listen for live channel events when watching a channel
    useEffect(() => {
        if (!channelKey) return

        // Clear previous events when switching channels
        channelEventsRef.current = []

        const handleEvent = (event: ChannelEvent) => {
            // Only accumulate events for the current channel
            if (event.channelKey === channelKey) {
                channelEventsRef.current.push(event)
                // Keep only the last 20 events to avoid context overflow
                if (channelEventsRef.current.length > 20) {
                    channelEventsRef.current = channelEventsRef.current.slice(-20)
                }
            }
        }

        window.qvacAPI.onChannelEvent(handleEvent)

        return () => {
            window.qvacAPI.removeChannelEventListener()
        }
    }, [channelKey])

    return (
        <div className="flex flex-col h-full bg-[#0F0F0F]">
            {/* Main Chat Interface Layout */}
            <div className="flex-1 overflow-hidden relative">
                {modelStatus === 'idle' ? (
                    <div className="flex flex-col items-center justify-center h-full bg-[#0F0F0F] text-neutral-400 gap-4">
                        <p className="text-sm">Local AI Model is not loaded.</p>
                        <button
                            onClick={loadModel}
                            className="bg-indigo-500 hover:bg-indigo-600 text-white px-4 py-2 rounded-full text-sm font-medium transition-colors"
                        >
                            Download & Load Model
                        </button>
                    </div>
                ) : modelStatus === 'downloading' ? (
                    <div className="flex flex-col items-center justify-center h-full bg-[#0F0F0F] text-neutral-400 gap-4">
                        <p className="text-sm text-center">
                            Downloading Local AI Model...<br/>
                            <span className="text-xs text-neutral-500">This may take a while depending on your connection.</span>
                        </p>
                        <div className="w-48 h-2 bg-neutral-800 rounded-full overflow-hidden mt-2 relative">
                            <div
                                className="h-full bg-indigo-500 transition-all duration-300"
                                style={{ width: `${modelProgress}%` }}
                            />
                        </div>
                        <p className="text-xs font-mono">{Math.round(modelProgress)}%</p>
                    </div>
                ) : (
                    /* Tailoring assistant-ui styles to sit perfectly inside the dark YouTube design language */
                    <div className="h-full w-full [&_.aui-thread]:h-full [&_.aui-thread]:bg-[#0F0F0F] [&_.aui-thread-viewport]:px-4 [&_.aui-text-muted]:text-neutral-500">
                        <AssistantRuntimeProvider runtime={runtime}>
                            <Thread />
                        </AssistantRuntimeProvider>
                    </div>
                )}
            </div>
        </div>
    )
}