import React from 'react'
import { AssistantRuntimeProvider, useLocalRuntime } from '@assistant-ui/react'
import { Thread } from './assistant-ui/thread' // Scaffolding generated by 'npx assistant-ui init'
import { qvacModelAdapter } from '../lib/qvac-adapter'

interface ChatInterfaceProps {
    loading: boolean
}

export function ChatInterface({ loading }: ChatInterfaceProps): React.JSX.Element {
    // Use the high-performance async generator adapter wired into the QVAC IPC stream
    const runtime = useLocalRuntime(qvacModelAdapter)

    return (
        <div className="flex flex-col h-full bg-[#0F0F0F]">
            {/* Main Chat Interface Layout */}
            <div className="flex-1 overflow-hidden relative">
                {loading ? (
                    <div className="flex items-center justify-center h-full bg-[#0F0F0F]">
                        <div className="flex gap-1">
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:0ms]" />
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:150ms]" />
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:300ms]" />
                        </div>
                    </div>
                ) : (
                    /* Tailoring assistant-ui styles to sit perfectly inside the dark YouTube design language */
                    <div className="h-full w-full [&_.aui-thread]:h-full [&_.aui-thread]:bg-[#0F0F0F] [&_.aui-thread-viewport]:px-4 [&_.aui-text-muted]:text-neutral-500">
                        <AssistantRuntimeProvider runtime={runtime}>
                            <Thread />
                        </AssistantRuntimeProvider>
                    </div>
                )}
            </div>
        </div>
    )
}