import React, { useEffect, useRef } from 'react'
import { AssistantRuntimeProvider, useLocalRuntime } from '@assistant-ui/react'
import { Thread } from './assistant-ui/thread' // Scaffolding generated by 'npx assistant-ui init'
import { createQvacModelAdapter } from '../lib/qvac-adapter'
import type { ChannelEvent } from '../../../shared/types'

interface ChatInterfaceProps {
    loading: boolean
    channelKey?: string | null
}

export function ChatInterface({ loading, channelKey }: ChatInterfaceProps): React.JSX.Element {
    // Accumulate channel events for AI context injection
    const channelEventsRef = useRef<ChannelEvent[]>([])

    // Create the adapter with a ref to the events buffer
    const adapter = React.useMemo(
        () => createQvacModelAdapter(channelEventsRef),
        []
    )

    const runtime = useLocalRuntime(adapter)

    // Listen for live channel events when watching a channel
    useEffect(() => {
        if (!channelKey) return

        // Clear previous events when switching channels
        channelEventsRef.current = []

        const handleEvent = (event: ChannelEvent) => {
            // Only accumulate events for the current channel
            if (event.channelKey === channelKey) {
                channelEventsRef.current.push(event)
                // Keep only the last 20 events to avoid context overflow
                if (channelEventsRef.current.length > 20) {
                    channelEventsRef.current = channelEventsRef.current.slice(-20)
                }
            }
        }

        window.qvacAPI.onChannelEvent(handleEvent)

        return () => {
            window.qvacAPI.removeChannelEventListener()
        }
    }, [channelKey])

    return (
        <div className="flex flex-col h-full bg-[#0F0F0F]">
            {/* Main Chat Interface Layout */}
            <div className="flex-1 overflow-hidden relative">
                {loading ? (
                    <div className="flex items-center justify-center h-full bg-[#0F0F0F]">
                        <div className="flex gap-1">
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:0ms]" />
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:150ms]" />
                            <span className="w-1.5 h-1.5 rounded-full bg-neutral-600 animate-bounce [animation-delay:300ms]" />
                        </div>
                    </div>
                ) : (
                    /* Tailoring assistant-ui styles to sit perfectly inside the dark YouTube design language */
                    <div className="h-full w-full [&_.aui-thread]:h-full [&_.aui-thread]:bg-[#0F0F0F] [&_.aui-thread-viewport]:px-4 [&_.aui-text-muted]:text-neutral-500">
                        <AssistantRuntimeProvider runtime={runtime}>
                            <Thread />
                        </AssistantRuntimeProvider>
                    </div>
                )}
            </div>
        </div>
    )
}